-- Domain integrity, normalized relationships, integer money, event history,
-- and atomic quote/invoice persistence.

alter table public.quotes add column if not exists client_id uuid references public.clients(id) on delete set null;
alter table public.invoices add column if not exists client_id uuid references public.clients(id) on delete set null;

alter table public.quotes add column if not exists subtotal_cents bigint;
alter table public.quotes add column if not exists overhead_cents bigint;
alter table public.quotes add column if not exists tax_cents bigint;
alter table public.quotes add column if not exists total_cents bigint;
alter table public.invoices add column if not exists subtotal_cents bigint;
alter table public.invoices add column if not exists overhead_cents bigint;
alter table public.invoices add column if not exists tax_cents bigint;
alter table public.invoices add column if not exists total_cents bigint;
alter table public.quote_items add column if not exists rate_cents bigint;
alter table public.quote_items add column if not exists client_rate_cents bigint;
alter table public.quote_items add column if not exists amount_cents bigint;
alter table public.invoice_items add column if not exists rate_cents bigint;
alter table public.invoice_items add column if not exists client_rate_cents bigint;
alter table public.invoice_items add column if not exists amount_cents bigint;
alter table public.expenses add column if not exists amount_cents bigint;

update public.quotes set
  subtotal_cents = round(coalesce(subtotal, 0) * 100),
  total_cents = round(coalesce(total, 0) * 100)
where subtotal_cents is null or total_cents is null;
update public.invoices set
  subtotal_cents = round(coalesce(subtotal, 0) * 100),
  total_cents = round(coalesce(total, 0) * 100)
where subtotal_cents is null or total_cents is null;
update public.quote_items set
  rate_cents = round(coalesce(rate, 0) * 100),
  client_rate_cents = round(coalesce(client_rate, rate, 0) * 100),
  amount_cents = round(coalesce(amount, 0) * 100)
where rate_cents is null or client_rate_cents is null or amount_cents is null;
update public.invoice_items set
  rate_cents = round(coalesce(rate, 0) * 100),
  client_rate_cents = round(coalesce(client_rate, rate, 0) * 100),
  amount_cents = round(coalesce(amount, 0) * 100)
where rate_cents is null or client_rate_cents is null or amount_cents is null;
update public.expenses set amount_cents = round(coalesce(amount, 0) * 100) where amount_cents is null;

alter table public.quotes alter column subtotal_cents set default 0;
alter table public.quotes alter column overhead_cents set default 0;
alter table public.quotes alter column tax_cents set default 0;
alter table public.quotes alter column total_cents set default 0;
alter table public.invoices alter column subtotal_cents set default 0;
alter table public.invoices alter column overhead_cents set default 0;
alter table public.invoices alter column tax_cents set default 0;
alter table public.invoices alter column total_cents set default 0;

alter table public.quotes drop constraint if exists quotes_status_allowed;
alter table public.quotes add constraint quotes_status_allowed
  check (status in ('Draft', 'Sent', 'Viewed', 'Accepted', 'Declined', 'Expired', 'Converted')) not valid;
alter table public.invoices drop constraint if exists invoices_status_allowed;
alter table public.invoices add constraint invoices_status_allowed
  check (status in ('Draft', 'Unpaid', 'Sent', 'Viewed', 'Partial', 'Paid', 'Overdue', 'Void')) not valid;

create index if not exists quotes_user_client_idx on public.quotes(user_id, client_id);
create index if not exists invoices_user_client_idx on public.invoices(user_id, client_id);
create index if not exists invoices_user_status_date_idx on public.invoices(user_id, status, date);
create index if not exists expenses_user_date_idx on public.expenses(user_id, date);

create table if not exists public.document_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null check (document_type in ('quote', 'invoice')),
  document_id uuid not null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists document_events_document_idx
  on public.document_events(user_id, document_type, document_id, created_at desc);
alter table public.document_events enable row level security;
drop policy if exists "app_document_events_owner" on public.document_events;
create policy "app_document_events_owner" on public.document_events
  for select to authenticated using (user_id = (select auth.uid()));

create or replace function public.record_document_status_event()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.document_events(user_id, document_type, document_id, event_type, metadata)
    values (new.user_id, case when tg_table_name = 'quotes' then 'quote' else 'invoice' end,
      new.id, 'created', jsonb_build_object('status', new.status));
  elsif new.status is distinct from old.status then
    insert into public.document_events(user_id, document_type, document_id, event_type, metadata)
    values (new.user_id, case when tg_table_name = 'quotes' then 'quote' else 'invoice' end,
      new.id, 'status_changed', jsonb_build_object('from', old.status, 'to', new.status));
  end if;
  return new;
end;
$$;
revoke all on function public.record_document_status_event() from public;
drop trigger if exists record_quote_status_event on public.quotes;
create trigger record_quote_status_event after insert or update of status on public.quotes
  for each row execute function public.record_document_status_event();
drop trigger if exists record_invoice_status_event on public.invoices;
create trigger record_invoice_status_event after insert or update of status on public.invoices
  for each row execute function public.record_document_status_event();

create or replace function public.save_quote_with_items(document jsonb, items jsonb)
returns uuid language plpgsql set search_path = '' as $$
declare
  owner_id uuid := auth.uid();
  document_id uuid;
  item jsonb;
begin
  if owner_id is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if nullif(document->>'client_id', '') is not null and not exists (
    select 1 from public.clients where id = (document->>'client_id')::uuid and user_id = owner_id
  ) then
    raise exception 'Client not found' using errcode = 'P0002';
  end if;
  document_id := nullif(document->>'id', '')::uuid;
  if document_id is null then
    insert into public.quotes(
      user_id, client_id, quote_num, status, date, valid_days, job_desc,
      client_name, client_phone, client_email, job_address,
      biz_name, biz_phone, biz_email, biz_address, biz_license, notes,
      tax_enabled, tax_rate, subtotal, total, overhead_percent, overhead_visible,
      subtotal_cents, overhead_cents, tax_cents, total_cents
    ) values (
      owner_id, nullif(document->>'client_id','')::uuid, document->>'quote_num', document->>'status',
      nullif(document->>'date','')::date, coalesce((document->>'valid_days')::int,30), document->>'job_desc',
      document->>'client_name', document->>'client_phone', document->>'client_email', document->>'job_address',
      document->>'biz_name', document->>'biz_phone', document->>'biz_email', document->>'biz_address', document->>'biz_license', document->>'notes',
      coalesce((document->>'tax_enabled')::boolean,false), coalesce((document->>'tax_rate')::numeric,0),
      coalesce((document->>'subtotal')::numeric,0), coalesce((document->>'total')::numeric,0),
      coalesce((document->>'overhead_percent')::numeric,0), coalesce((document->>'overhead_visible')::boolean,false),
      coalesce((document->>'subtotal_cents')::bigint,0), coalesce((document->>'overhead_cents')::bigint,0),
      coalesce((document->>'tax_cents')::bigint,0), coalesce((document->>'total_cents')::bigint,0)
    ) returning id into document_id;
  else
    update public.quotes set
      client_id=nullif(document->>'client_id','')::uuid, quote_num=document->>'quote_num', status=document->>'status',
      date=nullif(document->>'date','')::date, valid_days=coalesce((document->>'valid_days')::int,30), job_desc=document->>'job_desc',
      client_name=document->>'client_name', client_phone=document->>'client_phone', client_email=document->>'client_email', job_address=document->>'job_address',
      biz_name=document->>'biz_name', biz_phone=document->>'biz_phone', biz_email=document->>'biz_email', biz_address=document->>'biz_address',
      biz_license=document->>'biz_license', notes=document->>'notes', tax_enabled=coalesce((document->>'tax_enabled')::boolean,false),
      tax_rate=coalesce((document->>'tax_rate')::numeric,0), subtotal=coalesce((document->>'subtotal')::numeric,0),
      total=coalesce((document->>'total')::numeric,0), overhead_percent=coalesce((document->>'overhead_percent')::numeric,0),
      overhead_visible=coalesce((document->>'overhead_visible')::boolean,false), subtotal_cents=coalesce((document->>'subtotal_cents')::bigint,0),
      overhead_cents=coalesce((document->>'overhead_cents')::bigint,0), tax_cents=coalesce((document->>'tax_cents')::bigint,0),
      total_cents=coalesce((document->>'total_cents')::bigint,0), updated_at=now()
    where id=document_id and user_id=owner_id;
    if not found then raise exception 'Quote not found' using errcode='P0002'; end if;
  end if;
  delete from public.quote_items where quote_id=document_id;
  for item in select value from jsonb_array_elements(coalesce(items,'[]'::jsonb)) loop
    insert into public.quote_items(quote_id,sort_order,description,unit,qty,rate,amount,source_name,note,line_type,markup_enabled,markup_mode,markup_value,client_rate,rate_cents,client_rate_cents,amount_cents)
    values(document_id,coalesce((item->>'sort_order')::int,0),item->>'description',item->>'unit',coalesce((item->>'qty')::numeric,0),
      coalesce((item->>'rate')::numeric,0),coalesce((item->>'amount')::numeric,0),item->>'source_name',item->>'note',item->>'line_type',
      coalesce((item->>'markup_enabled')::boolean,false),item->>'markup_mode',coalesce((item->>'markup_value')::numeric,0),coalesce((item->>'client_rate')::numeric,0),
      coalesce((item->>'rate_cents')::bigint,0),coalesce((item->>'client_rate_cents')::bigint,0),coalesce((item->>'amount_cents')::bigint,0));
  end loop;
  return document_id;
end;
$$;

create or replace function public.save_invoice_with_items(document jsonb, items jsonb)
returns uuid language plpgsql set search_path = '' as $$
declare owner_id uuid := auth.uid(); document_id uuid; item jsonb;
begin
  if owner_id is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if nullif(document->>'client_id', '') is not null and not exists (
    select 1 from public.clients where id = (document->>'client_id')::uuid and user_id = owner_id
  ) then
    raise exception 'Client not found' using errcode='P0002';
  end if;
  if nullif(document->>'from_quote_id', '') is not null and not exists (
    select 1 from public.quotes where id = (document->>'from_quote_id')::uuid and user_id = owner_id
  ) then
    raise exception 'Source quote not found' using errcode='P0002';
  end if;
  document_id := nullif(document->>'id','')::uuid;
  if document_id is null then
    insert into public.invoices(user_id,client_id,invoice_num,status,date,due_days,due_date,job_desc,client_name,client_phone,client_email,job_address,biz_name,biz_phone,biz_email,biz_address,notes,tax_enabled,tax_rate,subtotal,total,from_quote_id,from_quote_num,overhead_percent,overhead_visible,subtotal_cents,overhead_cents,tax_cents,total_cents)
    values(owner_id,nullif(document->>'client_id','')::uuid,document->>'invoice_num',document->>'status',nullif(document->>'date','')::date,coalesce((document->>'due_days')::int,30),nullif(document->>'due_date','')::date,document->>'job_desc',document->>'client_name',document->>'client_phone',document->>'client_email',document->>'job_address',document->>'biz_name',document->>'biz_phone',document->>'biz_email',document->>'biz_address',document->>'notes',coalesce((document->>'tax_enabled')::boolean,false),coalesce((document->>'tax_rate')::numeric,0),coalesce((document->>'subtotal')::numeric,0),coalesce((document->>'total')::numeric,0),nullif(document->>'from_quote_id','')::uuid,document->>'from_quote_num',coalesce((document->>'overhead_percent')::numeric,0),coalesce((document->>'overhead_visible')::boolean,false),coalesce((document->>'subtotal_cents')::bigint,0),coalesce((document->>'overhead_cents')::bigint,0),coalesce((document->>'tax_cents')::bigint,0),coalesce((document->>'total_cents')::bigint,0)) returning id into document_id;
  else
    update public.invoices set client_id=nullif(document->>'client_id','')::uuid,invoice_num=document->>'invoice_num',status=document->>'status',date=nullif(document->>'date','')::date,due_days=coalesce((document->>'due_days')::int,30),due_date=nullif(document->>'due_date','')::date,job_desc=document->>'job_desc',client_name=document->>'client_name',client_phone=document->>'client_phone',client_email=document->>'client_email',job_address=document->>'job_address',biz_name=document->>'biz_name',biz_phone=document->>'biz_phone',biz_email=document->>'biz_email',biz_address=document->>'biz_address',notes=document->>'notes',tax_enabled=coalesce((document->>'tax_enabled')::boolean,false),tax_rate=coalesce((document->>'tax_rate')::numeric,0),subtotal=coalesce((document->>'subtotal')::numeric,0),total=coalesce((document->>'total')::numeric,0),from_quote_id=nullif(document->>'from_quote_id','')::uuid,from_quote_num=document->>'from_quote_num',overhead_percent=coalesce((document->>'overhead_percent')::numeric,0),overhead_visible=coalesce((document->>'overhead_visible')::boolean,false),subtotal_cents=coalesce((document->>'subtotal_cents')::bigint,0),overhead_cents=coalesce((document->>'overhead_cents')::bigint,0),tax_cents=coalesce((document->>'tax_cents')::bigint,0),total_cents=coalesce((document->>'total_cents')::bigint,0),updated_at=now() where id=document_id and user_id=owner_id;
    if not found then raise exception 'Invoice not found' using errcode='P0002'; end if;
  end if;
  delete from public.invoice_items where invoice_id=document_id;
  for item in select value from jsonb_array_elements(coalesce(items,'[]'::jsonb)) loop
    insert into public.invoice_items(invoice_id,sort_order,description,unit,qty,rate,amount,source_name,note,line_type,markup_enabled,markup_mode,markup_value,client_rate,rate_cents,client_rate_cents,amount_cents)
    values(document_id,coalesce((item->>'sort_order')::int,0),item->>'description',item->>'unit',coalesce((item->>'qty')::numeric,0),coalesce((item->>'rate')::numeric,0),coalesce((item->>'amount')::numeric,0),item->>'source_name',item->>'note',item->>'line_type',coalesce((item->>'markup_enabled')::boolean,false),item->>'markup_mode',coalesce((item->>'markup_value')::numeric,0),coalesce((item->>'client_rate')::numeric,0),coalesce((item->>'rate_cents')::bigint,0),coalesce((item->>'client_rate_cents')::bigint,0),coalesce((item->>'amount_cents')::bigint,0));
  end loop;
  return document_id;
end;
$$;

revoke all on function public.save_quote_with_items(jsonb,jsonb) from public;
grant execute on function public.save_quote_with_items(jsonb,jsonb) to authenticated;
revoke all on function public.save_invoice_with_items(jsonb,jsonb) from public;
grant execute on function public.save_invoice_with_items(jsonb,jsonb) to authenticated;
